name: Tests

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        run: forge fmt --check

      - name: Install dependencies
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes

      - name: Run tests
        run: forge test -vvv

      - name: Check gas snapshots
        run: forge snapshot --match-path test/integration/IntegrationTestGasComparisons.sol --snap .dex-comparisons -vvv
